apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: detective-archive
  namespace: cicd-services
spec:
  workspaces:
    - name: repo-pvc
    - name: git-auth
  params:
    - name: gitRepo
      type: string
      default: "https://code.boychai.xyz/BoyChai/Detective.git"
    - name: branch
      type: string
      default: "main"
    - name: imgTag
      type: string
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: repo-pvc
        - name: basic-auth
          workspace: git-auth
      params:
        - name: url
          value: $(params.gitRepo)
        - name: revision
          value: $(params.branch)
    - name: build
      params:
        - name: tag
          value: $(params.imgTag)
      workspaces:
        - name: source
          workspace: repo-pvc
      runAfter:
        - clone
      taskSpec:
        params:
          - name: tag
        workspaces:
          - name: source
        steps:
          - name: go-build
            workingDir: $(workspaces.source.path)
            image: golang:1.20
            env:
              - name: GOPROXY
                value: "https://goproxy.cn"
            script: |
              # 编译并构建 Windows x86 平台的可执行文件
              GOOS=windows GOARCH=amd64 go build -o archive/$(params.tag)/windows_amd64/detective.exe ./cli/build.go

              # 编译并构建 Linux x86 平台的可执行文件
              GOOS=linux GOARCH=amd64 go build -o archive/$(params.tag)/linux_amd64/detective ./cli/build.go

              # 编译并构建 macOS x86 平台的可执行文件
              GOOS=darwin GOARCH=amd64 go build -o archive/$(params.tag)/darwin_amd64/detective ./cli/build.go

              # 编译并构建 Windows ram 平台的可执行文件
              GOOS=windows GOARCH=arm go build -o archive/$(params.tag)/windows_arm/detective.exe ./cli/build.go

              # 编译并构建 Linux ram 平台的可执行文件
              GOOS=linux GOARCH=arm go build -o archive/$(params.tag)/linux_arm/detective ./cli/build.go

    - name: archive
      params:
        - name: tag
          value: $(params.imgTag)
      workspaces:
        - name: source
          workspace: repo-pvc
      runAfter:
        - build
      taskSpec:
        params:
          - name: tag
        workspaces:
          - name: source
        steps:
          - name: archive
            workingDir: $(workspaces.source.path)/archive/$(params.tag)
            image: registry.boychai.xyz/tools/zip:0.0.1
            script: |
              # win_amd64
              zip -j output/detective_$(params.tag)_windows_amd64.zip windows_amd64/detective.exe
              # lin_amd64
              tar -czf output/detective_$(params.tag)_linux_amd64.tar.gz -C linux_amd64/ detective
              # darwin_amd64
              tar -czf output/detective_$(params.tag)_darwin_amd64.tar.gz -C darwin_amd64/ detective
              # win_arm
              zip -j output/detective_$(params.tag)_windows_arm.zip windows_arm/detective.exe
              # lin_arm
              tar -czf output/detective_$(params.tag)_linux_arm.tar.gz -C linux_arm/ detective
